# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC12():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC12(self):
    self.driver.get("http://127.0.0.1:5000/loginForm")
    self.driver.set_window_size(1296, 696)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("xx@x@gd.#")
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Hola123!!")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("sample@example.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("sample")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    login = self.driver.find_element(By.TAG_NAME, "BUTTON").text
    assert 'Hello,\nSample' in login
